//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;

namespace Concesionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo : IEnumerable
    {
        public int idVehiculo { get; set; }
        public int idTipo { get; set; }
        public string matricula { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public double coste { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public IEnumerator GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }
}
